CREATE TABLE IF NOT EXISTS products (
  id VARCHAR(36),
  
  name VARCHAR(36),
  description VARCHAR(32),
  price FLOAT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  
  PRIMARY KEY(id)
);